name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - name: Set up Node.js 20.8.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      # Upload build artifacts for the publish job
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Semantic release needs the full git history
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - name: Set up Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      # Download the built artifacts
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
